[programs.localnet]
mycalculatordapp = "37EQMUeAn43KN9o65Cw3yhZV6sZo1YtVPegWwFNW1h1K"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/dhattarwalmohit/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
